[project]
name = "brickbreaker"
version = "0.1.0"
description = "A simple brick breaker game taken to 100%"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
